export const FETCH_COORDINATES = "FETCH_COORDINATES";
export const SAVE_COORDINATES = "SAVE_COORDINATES";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_STATE_ERRORS = "SET_STATE_ERRORS";
export const SET_NAVBAR = "SET_NAVBAR";